
language: generic

git:
  submodules: false

before_install:
- sudo apt-get update
- sudo apt-get install -y libx11-dev libxkbfile-dev
- sed -i "s/git@github.com:/https:\/\/benhutchison:$GHTOK@github.com\//" .gitmodules
- cat .gitmodules
- git submodule update --init --recursive
- curl -o- -L https://yarnpkg.com/install.sh | bash
- export PATH="$HOME/.yarn/bin:$PATH"

script: bash ./extract_monaco_sources.sh


env:
  global:
    secure: DA3UkbJZw2GAp1k2Qxsfkk/j6szgFglovJCw4+KDQuJIW03/qWef3OLYue2tDOvKIV7X2lQrNwGPWwF/k8ksmQo5frMMhxa3zITCCrpkH0scZA3TaYkvanHV2QffNRTa9T6Hbk2euPvU2tWf8yzPFH9TuYGDjwChEP7ZEmE+WzTPzlXwP0LdiebgQ1xiJZB6KGnqaq6GdAWR7Z9SFZnUvUsMYQy51CHOOiT0X46xq5gxooLGitkyiGAG6cEiXCda394EfrdaPGzS66Ucwfxjycnaz+RRjp9iG7sKzkbq1WVp1mbE0PWOdmp3xn6RlqVtoywrJfkNmO4M4RUMmm2jcLj81ztGE/5mcVv+EHkLNaFfqLoMok5YVmd0XZXm50M/NkW9Yc//CaFGSdUL7v8JhTxrKVbutEV5Qlw8KQ88q8l0kgRee2bbNub1iHxgn8988AKktH+xFK1lTiw22KXh8zz8kQ4mGwCvAqRPsyzwR7kCEjl0PNFs9YYWoZmrwqk6tkMW6dUW1Dvaqw+e6OQpzcF+tu+LdObi11SoUf/LECIshvpNo5Md8aCtfHQmlThbKo4vJ5pliD7A50p7m7ntng3EkbqZJ/3QSzo0AiqoC3EDfF58crNzGC2HN096OkIy0qq6p0hAzD+VsiMTJuB338a4Rf4l0vUja1rLrRTDEuk=
